### ISSUE TITLE
Randomizer testing

### ISSUE THREAD

**Issue by jwbowers** [thepolicylab/pvdtalks-randomization#2]
@khwilson @mcmcgrath13 and  (@matthewjlyddon  FYI)

I didn't want to clutter the main repo with results files, etc.. So I'm using this one. Happy to change.

Meanwhile, I looked at the treatment assignments of the datasets that I uploaded using `user-testing/randassess.py` (I put both the input and results files in this repo so I imagine you should be able to reproduce these results). So far it looks a bit less like urn-drawing and more like dice-rolling to me, but this is just a quick look. Is this what you expected to see?

By file uploaded: (Here I would have expected to always assign one of each of the three units to one of the three arms with n=3.)

```
pd.crosstab(index = dfbig["Assigned Arm"],columns=dfbig["fileabbrv"],margins=True)
Out[49]: 
fileabbrv     n_11  n_30  n_3a  n_3b  n_3c  n_4a  n_4b  n_4c  n_5  All
Assigned Arm                                                          
Arm 1            3     7     2     0     1     2     4     1    5   25
Arm 2            5    13     0     2     1     1     0     0    3   25
Arm 3            3    10     1     1     1     1     4     3    7   31
All             11    30     3     3     3     4     8     4   15   81
```

By size of file (combining all files of size 3 for example. If we had uploaded 10 such files we'd expect 10 in each arm). And I would not have expected only one unit assigned to Arm 2 from n=4.

```
pd.crosstab(index = dfbig["Assigned Arm"],columns=dfbig["n"],margins=True)
Out[48]: 
n             3   4   5  11  30  All
Assigned Arm                        
Arm 1         3   7   5   3   7   25
Arm 2         3   1   3   5  13   25
Arm 3         3   8   7   3  10   31
All           9  16  15  11  30   81
```

**Comment by khwilson** [comment]
Couple notes: there are actually two randomizers available: The "Hash" randomizer and the "Block" randomizer. The Block randomizer is essentially an urn drawing: it will do round robins (in blocks) so you'll always end up with an even distribution, though it has no memory so which arm it starts in is random and could conceivably cause imbalances.

The Hash randomizer is a dice roll, and so you can get slightly misbalanced.

The reason why we chose dice rolling is that we wanted _consistency_ of assignment but also didn't want a database. I don't think it's possible to do urn drawing given those conditions. However, if in practice this leads to distorted distributions, it's not too hard to implement a database, just mildly annoying. :-)

As for your numbers, you actually seem to have uploaded the same 4-size file (`4b`) twice, and so the 4-size numbers should be 5/1/6. That's a < 1% event, but not a < 0.1% event. Still may counsel for implementing the database.

**Comment by jwbowers** [comment]
I can see the issues with needing a database of unique ideas and
assignments. Seems a pain. I guess if we are assigning small numbers to
treatment, however, we don't want to have an arm that is empty (as can
occur with coin flipping/dice rolling). (Nice to know that I was right that
the Hash randomizer is a dice roller).

I'm tempted by the database, myself, as it would allow some other quality
checks. But I know even less about databases as I do with Google Script!

I did upload the same file twice as a check. But I shouldn't have analyzed
it as two different files. Thanks!

Jake Bowers
http://jakebowers.org

**Comment by jwbowers** [comment]
Closing this because we are archiving this, I assume. Unless we are writing up the cool tool. Even so, not sure this issue matters so closing.
